#
# pubspec for mt tool
#
name: mt
version: 0.0.3
description: >-
  A program to help manage monorepos.

environment:
  sdk: '>=2.12.0 <3.0.0'

executables:
  mt:

dependencies:
  path: ^1.7.0
  version: ^2.0.0
  args: ^2.1.1
  yaml: ^3.1.0
  ansicolor: ^2.0.1
  pub_api_client: ^2.1.0
  resource_portable: ^3.0.0

